### ISSUE TITLE
Create App

### ISSUE THREAD

**Issue by whois-marvin-42** [whois-marvin-42/learn-ror#1]
### Why ?
Creating the app, _"the right way"_ will help the process as changing the default after is a bit tedious/difficult in rails.

### Must have:
- [x] Postgresql
- [x] No front
- [x] No Tests framework

### Todo
- [x] Read through the `rails new --help` documentation
- [x] Create the app

#### What is rails api mode
- [x] http://guides.rubyonrails.org/api_app.html
#### What is a middleware
- [x] http://railscasts.com/episodes/151-rack-middleware
- [x] http://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack
