### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by whois-marvin-42** [whois-marvin-42/learn-ror#22]
## Why ?

Because we need the users to be authenticated to do certain actions.

## Must have

* [ ] A user model \o/
* [ ] Auth with: confirmation and login with email or username
  * [ ] Confirmation
  * [ ] Validation d'email
  * [ ] Reset password
* [ ] Postman

## Todo

I advise using my [fork](https://github.com/denispasin/devise_token_auth) of devise_auth_token (multiple bug/feature fixes rebased on last stable version). BUT I can understand that you prefer using the normal version of it. If you use my fork, please read the commits to understand how and why I fixed things.

* [ ] Add [Devise token auth](https://github.com/lynndylanhurley/devise_token_auth) (or my fork)
* [ ] Configure it
* [ ] Force users to be auth for accessing to lessons

## Reading list

* https://github.com/denispasin/devise_token_auth
