### ISSUE TITLE
Add policies

### ISSUE THREAD

**Issue by whois-marvin-42** [whois-marvin-42/learn-ror#24]
## Why ?

Because everyone isn't authorized to do everything.

## Must have

- [ ] Proper policies in place
- [ ] The API must nicely answer with `401` when unauthorized

## Todo

- [ ] Add [pundit](https://github.com/varvet/pundit) gem
- [ ] Write a policy so that only its creator can modify or delete a lesson
- [ ] Test it :D
