### ISSUE TITLE
Add policies

### ISSUE THREAD

**Issue by whois-marvin-42** [whois-marvin-42/learn-ror#29]
## Why ?

Because everyone isn't authorized to do everything.

## Must have

- [x] Proper policies in place
- [x] The API must nicely answer with `401` when unauthorized

## Todo

- [x] Add [pundit](https://github.com/varvet/pundit) gem
- [x] Write a policy so that only its creator can modify or delete a lesson
- [x] Test it :D
