### ISSUE TITLE
Add ActiveJob

### ISSUE THREAD

**Issue by whois-marvin-42** [whois-marvin-42/learn-ror#67]
### Why ?

Sending an email (see ticket #46) with Sendgrid take 1 to 2 sec each time. The user doesn't need to wait and the email can be sent asynchronously.

### Must have

- [ ] Sidekiq must be configured to work with ActiveJob
- [ ] All emails should be delivered later through Sidekiq/ActiveJob
- [ ] Plug it in Heroku
- [ ] If you have it make it work in Docker 

### Todo

- [ ] Configure sidekiq to work with active record (in dev) (see documentation lower)
- [ ] For processing emails with sidekiq dont forget to tell sidekiq that you want to process the mailer queue (`-q default -q mailers`)
- [ ] Email sent by devise token auth are sent with a `deliver_now`. To send them through sidekiq, define this in the `User` model: 
```ruby
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end
```
- [ ] A worker and the main rails process doesn't share a [SQL Transaction](https://www.tutorialspoint.com/sql/sql-transactions.html). So if you sent the emails in an after_create, you might have some fun and your worker might not find the invitation. Use after_commit instead (cf doc lower).
- [ ] To test and NOT use the sidekiq queue add at the end of your rails_helper.rb: 
```ruby
ActiveJob::Base.queue_adapter = :test
```

- [ ] When it's working in dev the fun part begin: Add Redis as an add-on to all of your heroku apps
- [ ] Add a `worker` line in your profile to launch sidekiq
- [ ] Each worker will connect to the DB and the number of connection is limited in a free heroku postgresql so limit the number of sidekiq workers to 10 (`-c 10`)
- [ ] Try your heroku config with `heroku local worker` (more info on this here: https://devcenter.heroku.com/articles/heroku-local)
- [ ] Deploy in staging and test it, then deploy in production.

### Reading List

- https://edgeguides.rubyonrails.org/active_job_basics.html;
- https://github.com/mperham/sidekiq/wiki/Active-Job;
- https://www.zaratan.fr/blog/2018/03/23/la-theorie-des-background-jobs/ (IE: why are we doing it this way);
- https://www.zaratan.fr/blog/2018/03/16/turtle-family-3-background-jobs/ (an example in turtle app).
- https://guides.rubyonrails.org/active_record_callbacks.html#transaction-callbacks
