### ISSUE TITLE
Deployement pipeline in Heroku

### ISSUE THREAD

**Issue by whois-marvin-42** [whois-marvin-42/learn-ror#8]
### Why ?
A fully automated deployment process will ensure that nobody ever push the wrong branch in deployment and will ensure that what is on Heroku is always up to date. It will also give us a staging env identical to production where we can test our feature one last time before updating the production (the only env clients see).

### Must have:
  - [x] Staging
  - [x] Prod
  - [x] Auto deploy master on Staging
  - [x] Deploy should run migrations

Each should have:

  - [x] Postgres

**Important**: Do not configure your term to be able to talk to heroku.

### Todo
  - [x] Create an heroku pipeline
  - [x] Create the staging app
  - [x] Create the prod app
  - [x] Add postgres on both
  - [x] Add a [Procfile](https://devcenter.heroku.com/articles/getting-started-with-rails5#procfile) to the App
  - [x] Configure ruby version to `2.5.1` (`.ruby-version`) and add it to the Gemfile (`ruby File.read('./.ruby-version')`)
  - [x] Configure ruby gemset so you know your gems are for this app only (`.ruby-gemset`)
  - [x] Add a release step in your procfile to run the migrations (https://devcenter.heroku.com/articles/release-phase)
  - [x] Configure heroku so it auto deploys master on staging.
  - [x] Deploy it
  - [x] Promote to production
  - [x] Check that everything is right by running a console in Staging and creating a Lesson with it.

### Reading list
- https://www.heroku.com/dynos
- https://devcenter.heroku.com/articles/pipelines
